Update user_guide.md
itsallcode/openfasttrace pull request #305
Opened 2021-12-22 02:36 UTC by jonathanvijayakumar

Added info about reportsettings and reportToPath, was useful for me, maybe for someone else also!
Added an extra hash for subtitle

2022-01-27 07:22 UTC, kaklakariada approved these changes

2022-01-31 14:27 UTC, redcatbear requested changes

2022-01-31 14:27 UTC, redcatbear commented on doc/user_guide.md
> +The ReportSettings builder has other functions as well that allow you to set verbosity etc.
```suggestion
The `ReportSettings` builder has other functions as well that allow you to set verbosity etc.
```

2022-03-11 16:39 UTC, kaklakariada approved these changes

2022-03-11 16:50 UTC, merged