Extended user_guide.md to explain keywords in specification items
itsallcode/openfasttrace pull request #328
Opened 2022-08-05 12:26 UTC by less0

I felt that the user guide did not explain well enough how to use keywords in specification items, which led me to open issue #325. After examining the source code I gained a better understanding on specification items and this is my attempt to explain them a bit better, especially the available keywords.

2022-08-12 14:51 UTC, kaklakariada requested changes
Thank you for the PR, looks good! I found only minor typos.
@redcatbear what do you think?

2022-08-12 14:51 UTC, kaklakariada commented on doc/user_guide.md
> +The `Covers` keyword states which items are covered by the current specification item. It is followed by a list of items that are covered, each one written on a new line starting witch a bullet chara
```suggestion
The `Covers` keyword states which items are covered by the current specification item. It is followed by a list of items that are covered, each one written on a new line starting with a bullet character (`+`, `*`, or `-`) followed by the referenced specification item id. 
```

2022-08-12 14:51 UTC, kaklakariada commented on doc/user_guide.md
> +The `Depends` keyword defines dependencies between specification items. It is followed by a list of items the current specification item depends on, each one written on a new line starting witch a bu
```suggestion
The `Depends` keyword defines dependencies between specification items. It is followed by a list of items the current specification item depends on, each one written on a new line starting witch a bullet character (`+`, `*`, or `-`) followed by the referenced specification item id. At the moment this has no effect on the HTML or plaintext output, but only if the `-o aspec` option is used. This has no effect on the coverage of specification items.
```

2022-08-13 17:45 UTC, redcatbear approved these changes

2022-08-14 09:14 UTC, kaklakariada approved these changes

2022-08-14 09:14 UTC, merged