Remove license header
itsallcode/openfasttrace pull request #331
Opened 2022-08-13 07:52 UTC by kaklakariada

The license header is only unnecessary clutter, we have the LICENSE.txt file anyway. The license plugin just annoys potential contributors with failing builds etc.

2022-08-13 18:11 UTC, redcatbear requested changes

2022-08-13 18:11 UTC, redcatbear commented on importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporterWithConfig.java
> +import static org.junit.jupiter.api.Assertions.assertThrows;import static org.mockito.Mockito.*;
```suggestion
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;
```

2022-08-13 18:11 UTC, redcatbear commented on product/src/test/java/org/itsallcode/openfasttrace/ITestSelfTrace.java
> +import java.io.UncheckedIOException;import java.nio.file.Files;
```suggestion
import java.io.UncheckedIOException;
import java.nio.file.Files;
```

2022-08-14 09:23 UTC, kaklakariada commented on importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporterWithConfig.java
> +import static org.junit.jupiter.api.Assertions.assertThrows;import static org.mockito.Mockito.*;
Good catch!

2022-08-14 09:23 UTC, merged