#338: Colored console report
itsallcode/openfasttrace pull request #349
Opened 2022-10-16 10:03 UTC by redcatbear

Closes #338.

2022-10-16 14:20 UTC, kaklakariada approved these changes

2022-10-16 14:20 UTC, kaklakariada commented on reporter/plaintext/src/test/java/org/itsallcode/openfasttrace/report/plaintext/TestTextFormatterFactory.java
> +    }
Add test for `null`

2022-10-16 14:21 UTC, kaklakariada requested changes
See review comments

2022-10-16 14:59 UTC, redcatbear commented on reporter/plaintext/src/test/java/org/itsallcode/openfasttrace/report/plaintext/TestTextFormatterFactory.java
> +    }
Done.

2022-11-20 10:13 UTC, redcatbear commented on core/src/test/java/org/itsallcode/openfasttrace/core/cli/TestCliArguments.java
> +    }
Removed.

2022-11-20 12:47 UTC, redcatbear commented on doc/spec/system_requirements.md
> +`List.of`
Fixed.

2022-11-20 18:08 UTC, kaklakariada approved these changes

2022-11-22 16:10 UTC, merged