Ignore spaces after items in "Needs:" and "Tags:" lists
itsallcode/openfasttrace pull request #373
Opened 2024-01-29 05:37 UTC by sambishop

This PR addresses issue 364: https://github.com/itsallcode/openfasttrace/issues/364

I noticed that "Tags" lists behave the same way, so I updated them as well.

2024-01-30 07:35 UTC, kaklakariada approved these changes

2024-01-31 22:58 UTC, sambishop commented
@kaklakariada, thank you for reviewing my PR.  But it's been stuck for over a day now waiting for the SonarCloud analysis, and I suspect that it's never going to complete.  Do you know how to get that step to run?

Also, I think this is a great project, so I thought I'd try addressing a few open issues as a way of showing my appreciation.  So let me know if there's anything I can improve.  I plan to open one PR per issue.  Thanks.

2024-02-02 06:44 UTC, kaklakariada commented
Hi @sambishop ,
thank you very much for your PR, we really appreciate that! I don't know how to solve the issue with the Sonar analysis. The token for Sonar is not available in external PR so we run it only when the token is available:

```yml
    - name: Sonar analysis
      shell: bash
      if: ${{ env.DEFAULT_OS == matrix.os && env.DEFAULT_JAVA == matrix.java && env.SONAR_TOKEN != null }}
      run: |
        mvn --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.token=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```
I guess the pragmatic solution would be to merge the PR anyway after a review.

Another thing: I would like to add an entry to the changelog for your changes. I will do that directly in your PR if that's OK for you.

2024-02-02 12:21 UTC, kaklakariada commented
I added tests and found a bug with parsing the `Tags:` field and fixed it.
@redcatbear Please also have a look at my changes.

2024-02-02 13:16 UTC, sambishop commented
I've never used Sonar on a public repo before.  I've tried adding a Sonar token secret to my forked repo, to see if that allows it to run.  And I've addressed the only two outstanding Sonar issues.  Let's see what happens.

Thanks again for your help, @kaklakariada!

2024-02-02 14:31 UTC, redcatbear requested changes
Looks really good! Thanks for the PR.

Couple small improvements suggested.

2024-02-02 14:31 UTC, redcatbear commented on importer/markdown/src/main/java/org/itsallcode/openfasttrace/importer/markdown/MdPattern.java
> +    NEEDS_INT("Needs:(\\s*\\w+\\s*(?:,\\s*\\w+\\s*)*)"),
:+1:

2024-02-02 14:31 UTC, redcatbear commented on importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/ITMarkdownImporter.java
> +                + " , " + NEEDS_ARTIFACT_TYPE2 + " ";
Good catch!

2024-02-02 14:31 UTC, redcatbear commented on importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/ITMarkdownImporter.java
> +        final InputFile file = StreamInput.forReader(Paths.get(FILENAME), reader);
No intermediate file on the file system. I like it.

2024-02-02 14:31 UTC, redcatbear commented on importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/ITMarkdownImporter.java
> +        // + " + " + TAG2 + "";
```suggestion

        // + "\nTags:\n" //
        // + " * " + TAG1 + "\n" //
        // + " + " + TAG2 + "";
```

Please remove commented code.

2024-02-02 14:31 UTC, redcatbear commented on importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/TestMarkdownImporter.java
> +        assertMismatch(MdPattern.NEEDS_INT, "Needs:");
We should wrap all of these with `assertAll(()-> ... )` so that all sub-asserts are always executed. Provides better debugging output.

2024-02-02 14:43 UTC, kaklakariada commented on doc/changes/changes.md
>  * [3.7.1](changes_3.7.1.md)
OFT 3.7.1 was released to Maven Central (https://repo1.maven.org/maven2/org/itsallcode/openfasttrace/openfasttrace-core/3.7.1/) and GitHub (https://github.com/itsallcode/openfasttrace/releases/tag/3.7.1), so the next release should be 3.7.2.

2024-02-02 15:04 UTC, merged