#413: Load plugins from JAR files
itsallcode/openfasttrace pull request #416
Opened 2024-06-16 10:53 UTC by kaklakariada

Closes #413

2024-07-17 08:45 UTC, redcatbear requested changes

2024-07-17 08:45 UTC, redcatbear commented on core/src/test/java/org/itsallcode/openfasttrace/core/serviceloader/ServiceLoaderFactoryTest.java
> +    private ServiceLoaderFactory testee()
```suggestion
    private ServiceLoaderFactory factory()
```

2024-07-17 08:45 UTC, redcatbear commented on core/src/test/java/org/itsallcode/openfasttrace/core/serviceloader/ServiceLoaderFactoryTest.java
> +        Files.delete(tempDir);
We discussed this and the intention was actually to use a non-existent.

So I would be better to use `resolve("non-exsistent-dir")` in the temp dir.

2024-07-17 08:45 UTC, redcatbear commented on core/src/test/java/org/itsallcode/openfasttrace/core/serviceloader/ServiceLoaderFactoryTest.java
> +                () -> assertThat(origins.get(0).getClassLoader().getName(), equalTo("app")));
Extract matcher from second assert. Wrap in `contains()`. Remove `hasSize(1)`.

2024-07-17 08:45 UTC, redcatbear commented on core/src/test/java/org/itsallcode/openfasttrace/core/serviceloader/ServiceLoaderFactoryTest.java
> +    void findServiceOriginsPluginDir()
If I look at the code below, this tests behavior on an *empty* plugins parent dir.

2024-07-17 08:45 UTC, redcatbear commented on core/src/test/java/org/itsallcode/openfasttrace/core/serviceloader/ServiceOriginTest.java
> +        verifyNoMoreInteractions(classLoaderMock);
:+1: Good. Normally I am not a fan of `verifyNoMoreInteractions`, but here it is absolutely justified.

2024-07-20 15:10 UTC, kaklakariada commented on core/src/test/java/org/itsallcode/openfasttrace/core/serviceloader/ServiceLoaderFactoryTest.java
> +    void findServiceMissingParentDir() throws IOException
I renamed the test to `findServiceMissingParentDirFindsNoPlugins()`

2024-08-11 07:06 UTC, redcatbear approved these changes

2024-08-11 07:34 UTC, merged